sudo: required  
cache: pip
os: linux
dist: bionic
language: python
python:
  - "3.6"
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
install:
  - sudo apt-get install libdb-dev
  - pip3 install cython
  - pip3 install -r requirements.txt
  - pip3 install -r optional-requirements.txt
  - pip3 install .
script:
  - py.test -s -vv bigsi/tests/
after_success:
    docker build --build-arg TRAVIS=true -t phelimb/bigsi:${COMMIT} .
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";  
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag phelimb/bigsi:${COMMIT} phelimb/bigsi:latest
    docker push phelimb/bigsi;
    else
    docker push phelimb/bigsi:${COMMIT};      
    fi

